### ISSUE TITLE
Confusing NO FILE error message for uppercase ext

### ISSUE THREAD

**Issue by phy25** [BUGenerator/Web#15]
When submitting a uppercase extension file like `test.PNG`, it fails. The extension check code should standardize the extension to all lowercase to compare with the allowed list.

https://github.com/BUGenerator/Web/blob/83897834046222089a50359bc6b051fe4fab46f5/upload.py#L17-L19

Also the error message is misleading. Sometimes people might use not-supported file format (e.g. webp), and it is different from not uploading the file. We might need to use more specific error messages?

**Comment by feiyue33** [comment]
For the uppercase extension, I add .lower() function in upload.py and it should work. I commit it in dev branch.

**Comment by phy25** [comment]
Duplicate of #11. Uppercase bug has been fixed.
